title: E-Portfolio TTI
description: Matthias Nitsche TTI E-Portfolio Haw Hamburg

# Use a 500x250 image
# default-image: tf.jpg

markdown: kramdown
permalink: /:title/
paginate: 3
paginate_path: /page:num/

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]
